import { App } from "@core/App.js";
import { Api } from "@modules/Api.js";
import { Auth } from "@modules/Auth.js";
import { Modal } from "@modules/Modal.js";
import { Router } from "@modules/Router.js";
import { UI } from "@modules/UI.js";
import { Header } from "@modules/Header.js";
import { Chart } from "@modules/Chart.js";
import { Watchlist } from "@modules/Watchlist.js";
import { StatsWidget } from "@modules/StatsWidget.js";
import { WebSocketManager } from "@modules/WebSocket.js";
import { Simulator } from "@modules/Simulator.js";
import { Indicators } from "@modules/Indicators.js";
import { Sound } from "@modules/Sound.js";
import { I18n } from "@modules/I18n.js";

const app = new App();
app.module("api", Api);
app.module("auth", Auth);
app.module("i18n", I18n);
app.module("ws", WebSocketManager);
app.module("modal", Modal);
app.module("header", Header);
app.module("watchlist", Watchlist);
app.module("stats", StatsWidget);
app.module("chart", Chart);
app.module("indicators", Indicators);
app.module("ui", UI);
app.module("sound", Sound);
app.module("simulator", Simulator);
app.module("router", Router);
app.init();
